name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Services Config
        id: createservicesconfig
        uses: kannan-xiao4/Unity-CreateServicesConfig-For-LicenseServer@main
        with:
          licensingServiceBaseUrl: 'http://{YOUR-LICENSE-SERVER-ADDRESS:PORT}'
          enableEntitlementLicensing: true
          enableFloatingApi: true
          clientConnectTimeoutSec: 5
          clientHandshakeTimeoutSec: 10

      - name: Setup Unity
        id: setup-unity
        uses: kuler90/setup-unity@v1.0.7
        with:
          project-path: ${{ github.workspace }}

      - name: Build Unity
        uses: kuler90/build-unity@v1
        with:
          project-path: ${{ github.workspace }}
          build-target: StandaloneLinux64

      - name: Archive build player results
        uses: actions/upload-artifact@v2
        with:
          name: buildplayer
          path: ${{ github.workspace }}/builds

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Create Services Config
  #       id: createservicesconfig
  #       uses: kannan-xiao4/Unity-CreateServicesConfig-For-LicenseServer@main
  #       with:
  #         licensingServiceBaseUrl: 'http://{YOUR-LICENSE-SERVER-ADDRESS:PORT}'
  #         enableEntitlementLicensing: true
  #         enableFloatingApi: true
  #         clientConnectTimeoutSec: 5
  #         clientHandshakeTimeoutSec: 10

  #     - name: Setup Unity
  #       id: setup-unity
  #       uses: kuler90/setup-unity@v1.0.7
  #       with:
  #         project-path: ${{ github.workspace }}

  #     - name: Build Unity
  #       uses: kuler90/build-unity@v1
  #       with:
  #         project-path: ${{ github.workspace }}
  #         build-target: StandaloneOSX

  #     - name: Archive build player results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: buildplayer
  #         path: ${{ github.workspace }}/builds

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Create Services Config
  #       id: createservicesconfig
  #       uses: kannan-xiao4/Unity-CreateServicesConfig-For-LicenseServer@main
  #       with:
  #         licensingServiceBaseUrl: 'http://{YOUR-LICENSE-SERVER-ADDRESS:PORT}'
  #         enableEntitlementLicensing: true
  #         enableFloatingApi: true
  #         clientConnectTimeoutSec: 5
  #         clientHandshakeTimeoutSec: 10

  #     - name: Setup Unity
  #       id: setup-unity
  #       uses: kuler90/setup-unity@v1.0.7
  #       with:
  #         project-path: ${{ github.workspace }}

  #     - name: Build Unity
  #       uses: kuler90/build-unity@v1
  #       with:
  #         project-path: ${{ github.workspace }}
  #         build-target: StandaloneWindows64

  #     - name: Archive build player results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: buildplayer
  #         path: ${{ github.workspace }}\builds
